//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DTicTacToe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3DTicTacToe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Each row represents a triplet that can be used to win the game
        ///#first square only
        ///0, 1, 2
        ///3, 4, 5
        ///6, 7, 8
        ///0, 3, 6
        ///1, 4, 7
        ///2, 5, 8
        ///0, 4, 8
        ///2, 4, 6
        ///#second square only
        ///9, 10, 11
        ///12, 13, 14
        ///15, 16, 17
        ///9, 12, 15
        ///10, 13, 16
        ///11, 14, 17
        ///9, 13, 17
        ///11, 13, 15
        ///#third square only
        ///18, 19, 20
        ///21, 22, 23
        ///24, 25, 26
        ///18, 21, 24
        ///19, 22, 25
        ///20, 23, 26
        ///18, 22, 26
        ///20, 22, 24
        ///#vertically through the cube
        ///0, 9, 18
        ///1, 10, 19
        ///2, 11, 20
        ///3, 12, 21
        ///4, 13, 22
        ///5, 14, 23
        ///6, 15, 24
        ///7, 16, 25
        ///8, 17, 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WinningCombinations {
            get {
                return ResourceManager.GetString("WinningCombinations", resourceCulture);
            }
        }
    }
}
